CREATE DATABASE IF NOT EXISTS DQ_DEMO;
CREATE SCHEMA IF NOT EXISTS DQ_DEMO.SALES;
USE DATABASE DQ_DEMO;
USE SCHEMA SALES;




CREATE OR REPLACE TABLE RAW_CUSTOMERS (
    CUSTOMER_ID         VARCHAR(20),
    FIRST_NAME          VARCHAR(100),
    LAST_NAME           VARCHAR(100),
    EMAIL               VARCHAR(255),
    PHONE               VARCHAR(30),
    PROVINCE            VARCHAR(50),
    POSTAL_CODE         VARCHAR(10),
    DATE_OF_BIRTH       VARCHAR(20),   
    CUSTOMER_SEGMENT    VARCHAR(50),
    CREATED_DATE        VARCHAR(20),
    ANNUAL_SPEND_CAD    VARCHAR(20)    


-- PRODUCTS

CREATE OR REPLACE TABLE RAW_PRODUCTS (
    PRODUCT_ID          VARCHAR(20),
    PRODUCT_NAME        VARCHAR(200),
    CATEGORY            VARCHAR(50),
    SUB_CATEGORY        VARCHAR(50),
    UNIT_PRICE_CAD      VARCHAR(20),   
    ALCOHOL_PCT         VARCHAR(10),   
    SUPPLIER_CODE       VARCHAR(20),
    IS_ACTIVE           VARCHAR(10),
    LISTED_DATE         VARCHAR(20)
);


-- ORDERS

CREATE OR REPLACE TABLE RAW_ORDERS (
    ORDER_ID            VARCHAR(20),
    CUSTOMER_ID         VARCHAR(20),
    PRODUCT_ID          VARCHAR(20),
    ORDER_DATE          VARCHAR(20),  
    QUANTITY            VARCHAR(10),  
    UNIT_PRICE_CAD      VARCHAR(20),   
    TOTAL_AMOUNT_CAD    VARCHAR(20),   
    CHANNEL             VARCHAR(30),
    PROVINCE            VARCHAR(50),
    SALES_REP_ID        VARCHAR(20),
    STATUS              VARCHAR(20)
);