-- CUSTOMER DQ RULES VIEW

CREATE OR REPLACE VIEW VW_CUSTOMER_DQ AS
WITH VALID_PROVINCES AS (
    SELECT column1 AS prov
    FROM (VALUES ('AB'),('BC'),('MB'),('NB'),('NL'),('NS'),('NT'),('NU'),('ON'),('PE'),('QC'),('SK'),('YT'))
)
SELECT
    CUSTOMER_ID,
    FIRST_NAME,
    LAST_NAME,
    EMAIL,
    PHONE,
    PROVINCE,
    DATE_OF_BIRTH,
    ANNUAL_SPEND_CAD,
    CUSTOMER_SEGMENT,
    CREATED_DATE,

    -- COMPLETENESS 
    CASE WHEN CUSTOMER_ID IS NULL OR TRIM(CUSTOMER_ID) = '' THEN 'FAIL' ELSE 'PASS' END AS chk_customer_id_not_null,
    CASE WHEN FIRST_NAME  IS NULL OR TRIM(FIRST_NAME)  = '' THEN 'FAIL' ELSE 'PASS' END AS chk_first_name_not_null,
    CASE WHEN LAST_NAME   IS NULL OR TRIM(LAST_NAME)   = '' THEN 'FAIL' ELSE 'PASS' END AS chk_last_name_not_null,
    CASE WHEN EMAIL       IS NULL OR TRIM(EMAIL)       = '' THEN 'FAIL' ELSE 'PASS' END AS chk_email_not_null,

    -- UNIQUENESS 
    CASE WHEN COUNT(*) OVER (PARTITION BY CUSTOMER_ID) > 1 THEN 'FAIL' ELSE 'PASS' END AS chk_customer_id_unique,

    -- Email format 
    CASE WHEN NOT REGEXP_LIKE(EMAIL, '^[A-Za-z0-9._%+\\-]+@[A-Za-z0-9.\\-]+\\.[A-Za-z]{2,}$')
              OR EMAIL IS NULL THEN 'FAIL' ELSE 'PASS' END AS chk_email_format,

    -- Phone format 
    CASE WHEN NOT REGEXP_LIKE(PHONE, '^[0-9]{3}-[0-9]{3}-[0-9]{4}$')
              OR PHONE IS NULL THEN 'FAIL' ELSE 'PASS' END AS chk_phone_format,

    -- Province is a real Canadian province
    CASE WHEN PROVINCE NOT IN (SELECT prov FROM VALID_PROVINCES)
              OR PROVINCE IS NULL THEN 'FAIL' ELSE 'PASS' END AS chk_province_valid,

    -- ANNUAL_SPEND_CAD is numeric and >= 0
    CASE WHEN TRY_TO_NUMBER(ANNUAL_SPEND_CAD) IS NULL  THEN 'FAIL'
         WHEN TRY_TO_NUMBER(ANNUAL_SPEND_CAD) < 0  THEN 'FAIL'
         ELSE 'PASS' END  AS chk_spend_numeric_positive,

    -- DATE_OF_BIRTH is not in the future
    CASE WHEN TRY_TO_DATE(DATE_OF_BIRTH) IS NULL THEN 'FAIL'
         WHEN TRY_TO_DATE(DATE_OF_BIRTH) > CURRENT_DATE() THEN 'FAIL'
         WHEN TRY_TO_DATE(DATE_OF_BIRTH) < '1900-01-01' THEN 'FAIL'
         ELSE 'PASS' END  AS chk_dob_valid,

    -- OVERALL ROW SCORE
    CASE WHEN
        (CASE WHEN CUSTOMER_ID IS NULL OR TRIM(CUSTOMER_ID)='' THEN 1 ELSE 0 END +
         CASE WHEN FIRST_NAME  IS NULL OR TRIM(FIRST_NAME) ='' THEN 1 ELSE 0 END +
         CASE WHEN LAST_NAME   IS NULL OR TRIM(LAST_NAME)  ='' THEN 1 ELSE 0 END +
         CASE WHEN EMAIL       IS NULL OR TRIM(EMAIL)      ='' THEN 1 ELSE 0 END +
         CASE WHEN COUNT(*) OVER (PARTITION BY CUSTOMER_ID) > 1 THEN 1 ELSE 0 END +
         CASE WHEN NOT REGEXP_LIKE(COALESCE(EMAIL,'x'), '^[A-Za-z0-9._%+\\-]+@[A-Za-z0-9.\\-]+\\.[A-Za-z]{2,}$') THEN 1 ELSE 0 END +
         CASE WHEN NOT REGEXP_LIKE(COALESCE(PHONE,'x'), '^[0-9]{3}-[0-9]{3}-[0-9]{4}$') THEN 1 ELSE 0 END +
         CASE WHEN TRY_TO_NUMBER(ANNUAL_SPEND_CAD) IS NULL OR TRY_TO_NUMBER(ANNUAL_SPEND_CAD) < 0 THEN 1 ELSE 0 END +
         CASE WHEN TRY_TO_DATE(DATE_OF_BIRTH) IS NULL OR TRY_TO_DATE(DATE_OF_BIRTH) > CURRENT_DATE() THEN 1 ELSE 0 END
        ) = 0
    THEN 'CLEAN' ELSE 'FLAGGED' END AS row_dq_status

FROM RAW_CUSTOMERS;


select * from VW_CUSTOMER_DQ;




-- PRODUCT DQ RULES VIEW

CREATE OR REPLACE VIEW VW_PRODUCT_DQ AS
WITH VALID_CATEGORIES AS (
    SELECT column1 AS cat FROM (VALUES ('Beer'),('Spirits'),('Wine'),('Cider'),('Cooler'))
)
SELECT
    PRODUCT_ID,
    PRODUCT_NAME,
    CATEGORY,
    UNIT_PRICE_CAD,
    ALCOHOL_PCT,
    IS_ACTIVE,
    SUPPLIER_CODE,

    -- ── COMPLETENESS
    CASE WHEN PRODUCT_ID   IS NULL OR TRIM(PRODUCT_ID)   = '' THEN 'FAIL' ELSE 'PASS' END AS chk_product_id_not_null,
    CASE WHEN PRODUCT_NAME IS NULL OR TRIM(PRODUCT_NAME) = '' THEN 'FAIL' ELSE 'PASS' END AS chk_product_name_not_null,

    -- ── UNIQUENESS 
    CASE WHEN COUNT(*) OVER (PARTITION BY PRODUCT_ID) > 1 THEN 'FAIL' ELSE 'PASS' END AS chk_product_id_unique,

    -- Price must be numeric and > 0 
    CASE WHEN TRY_TO_NUMBER(UNIT_PRICE_CAD) IS NULL THEN 'FAIL'
         WHEN TRY_TO_NUMBER(UNIT_PRICE_CAD) <= 0 THEN 'FAIL'
         ELSE 'PASS' END  AS chk_price_positive,

    -- Alcohol % between 0 and 96 
    CASE WHEN TRY_TO_NUMBER(ALCOHOL_PCT) IS NULL THEN 'FAIL'
         WHEN TRY_TO_NUMBER(ALCOHOL_PCT) < 0 THEN 'FAIL'
         WHEN TRY_TO_NUMBER(ALCOHOL_PCT) > 96 THEN 'FAIL'
         ELSE 'PASS' END AS chk_alcohol_pct_valid,

    -- IS_ACTIVE must be Y or N 
    CASE WHEN IS_ACTIVE NOT IN ('Y','N')
              OR IS_ACTIVE IS NULL  THEN 'FAIL' ELSE 'PASS' END AS chk_is_active_valid,

    -- VALIDITY: Category in approved list
    CASE WHEN CATEGORY NOT IN (SELECT cat FROM VALID_CATEGORIES)
              OR CATEGORY IS NULL THEN 'FAIL' ELSE 'PASS' END AS chk_category_valid,

    -- OVERALL ROW SCORE
    CASE WHEN
        (CASE WHEN PRODUCT_ID   IS NULL OR TRIM(PRODUCT_ID)='' THEN 1 ELSE 0 END +
         CASE WHEN PRODUCT_NAME IS NULL OR TRIM(PRODUCT_NAME)='' THEN 1 ELSE 0 END +
         CASE WHEN COUNT(*) OVER (PARTITION BY PRODUCT_ID) > 1   THEN 1 ELSE 0 END +
         CASE WHEN TRY_TO_NUMBER(UNIT_PRICE_CAD) IS NULL OR TRY_TO_NUMBER(UNIT_PRICE_CAD) <= 0 THEN 1 ELSE 0 END +
         CASE WHEN TRY_TO_NUMBER(ALCOHOL_PCT) IS NULL OR TRY_TO_NUMBER(ALCOHOL_PCT) < 0 OR TRY_TO_NUMBER(ALCOHOL_PCT) > 96 THEN 1 ELSE 0 END +
         CASE WHEN IS_ACTIVE NOT IN ('Y','N') OR IS_ACTIVE IS NULL THEN 1 ELSE 0 END +
         CASE WHEN CATEGORY NOT IN (SELECT cat FROM VALID_CATEGORIES) OR CATEGORY IS NULL THEN 1 ELSE 0 END
        ) = 0
    THEN 'CLEAN' ELSE 'FLAGGED' END AS row_dq_status

FROM RAW_PRODUCTS;


select * from vw_product_dq;





-- ORDER DQ RULES VIEW

CREATE OR REPLACE VIEW VW_ORDER_DQ AS
WITH VALID_STATUS   AS (SELECT column1 AS s FROM (VALUES ('Completed'),('Pending'),('Cancelled'),('Refunded'))),
     VALID_CHANNEL  AS (SELECT column1 AS c FROM (VALUES ('Online'),('In-Store'),('VIP Portal')))
SELECT
    o.ORDER_ID,
    o.CUSTOMER_ID,
    o.PRODUCT_ID,
    o.ORDER_DATE,
    o.QUANTITY,
    o.UNIT_PRICE_CAD,
    o.TOTAL_AMOUNT_CAD,
    o.CHANNEL,
    o.STATUS,

    -- COMPLETENESS 
    CASE WHEN ORDER_ID   IS NULL OR TRIM(ORDER_ID) = ''   THEN 'FAIL' ELSE 'PASS' END AS chk_order_id_not_null,
    CASE WHEN CUSTOMER_ID IS NULL OR TRIM(CUSTOMER_ID)='' THEN 'FAIL' ELSE 'PASS' END AS chk_customer_id_not_null,
    CASE WHEN PRODUCT_ID IS NULL OR TRIM(PRODUCT_ID) ='' THEN 'FAIL' ELSE 'PASS' END AS chk_product_id_not_null,
    CASE WHEN ORDER_DATE IS NULL OR TRIM(ORDER_DATE) ='' THEN 'FAIL' ELSE 'PASS' END AS chk_order_date_not_null,

    -- Order date not in future 
    CASE WHEN TRY_TO_DATE(ORDER_DATE) IS NULL THEN 'FAIL'
         WHEN TRY_TO_DATE(ORDER_DATE) > CURRENT_DATE() THEN 'FAIL'
         ELSE 'PASS' END AS chk_order_date_not_future,

    -- VALIDITY: Quantity numeric and > 0 
    CASE WHEN TRY_TO_NUMBER(QUANTITY) IS NULL THEN 'FAIL'
         WHEN TRY_TO_NUMBER(QUANTITY) <= 0 THEN 'FAIL'
         ELSE 'PASS' END AS chk_quantity_positive,

    -- Total = Qty × Unit Price (±$0.02 rounding tolerance) ─
    CASE WHEN TRY_TO_NUMBER(QUANTITY)      IS NULL THEN 'FAIL'
         WHEN TRY_TO_NUMBER(UNIT_PRICE_CAD) IS NULL THEN 'FAIL'
         WHEN TRY_TO_NUMBER(TOTAL_AMOUNT_CAD) IS NULL THEN 'FAIL'
         WHEN ABS( TRY_TO_NUMBER(TOTAL_AMOUNT_CAD)
                 - (TRY_TO_NUMBER(QUANTITY) * TRY_TO_NUMBER(UNIT_PRICE_CAD))
                 ) > 0.02   THEN 'FAIL'
         ELSE 'PASS' END AS chk_total_matches_qty_price,

    -- Status in approved list
    CASE WHEN STATUS NOT IN (SELECT s FROM VALID_STATUS) OR STATUS IS NULL THEN 'FAIL' ELSE 'PASS' END AS chk_status_valid,

    -- Channel in approved list
    CASE WHEN CHANNEL NOT IN (SELECT c FROM VALID_CHANNEL) OR CHANNEL IS NULL THEN 'FAIL' ELSE 'PASS' END AS chk_channel_valid,

    --  FK to Customers 
    CASE WHEN NOT EXISTS (SELECT 1 FROM RAW_CUSTOMERS c WHERE c.CUSTOMER_ID = o.CUSTOMER_ID)
         THEN 'FAIL' ELSE 'PASS' END AS chk_customer_fk,

    -- FK to Products 
    CASE WHEN NOT EXISTS (SELECT 1 FROM RAW_PRODUCTS p WHERE p.PRODUCT_ID = o.PRODUCT_ID)
         THEN 'FAIL' ELSE 'PASS' END AS chk_product_fk,

    -- OVERALL ROW SCORE 
    CASE WHEN
        (CASE WHEN ORDER_ID IS NULL OR TRIM(ORDER_ID)='' THEN 1 ELSE 0 END +
         CASE WHEN ORDER_DATE IS NULL OR TRIM(ORDER_DATE)='' THEN 1 ELSE 0 END +
         CASE WHEN TRY_TO_DATE(ORDER_DATE) IS NULL OR TRY_TO_DATE(ORDER_DATE) > CURRENT_DATE() THEN 1 ELSE 0 END +
         CASE WHEN TRY_TO_NUMBER(QUANTITY) IS NULL OR TRY_TO_NUMBER(QUANTITY) <= 0 THEN 1 ELSE 0 END +
         CASE WHEN ABS(TRY_TO_NUMBER(TOTAL_AMOUNT_CAD) - (TRY_TO_NUMBER(QUANTITY)*TRY_TO_NUMBER(UNIT_PRICE_CAD))) > 0.02 THEN 1 ELSE 0 END +
         CASE WHEN STATUS NOT IN (SELECT s FROM VALID_STATUS) OR STATUS IS NULL THEN 1 ELSE 0 END +
         CASE WHEN CHANNEL NOT IN (SELECT c FROM VALID_CHANNEL) OR CHANNEL IS NULL THEN 1 ELSE 0 END +
         CASE WHEN NOT EXISTS (SELECT 1 FROM RAW_CUSTOMERS c WHERE c.CUSTOMER_ID = o.CUSTOMER_ID) THEN 1 ELSE 0 END +
         CASE WHEN NOT EXISTS (SELECT 1 FROM RAW_PRODUCTS p WHERE p.PRODUCT_ID = o.PRODUCT_ID) THEN 1 ELSE 0 END
        ) = 0
    THEN 'CLEAN' ELSE 'FLAGGED' END AS row_dq_status

FROM RAW_ORDERS o;


select * from vw_order_dq;