-- Overall DQ score by table and dimension 
SELECT
    TABLE_NAME,
    DQ_DIMENSION,
    CHECK_NAME,
    TOTAL_RECORDS,
    PASS_COUNT,
    FAIL_COUNT,
    PASS_PCT
FROM DQ_METRICS_LOG
WHERE RUN_TIMESTAMP = (SELECT MAX(RUN_TIMESTAMP) FROM DQ_METRICS_LOG)
ORDER BY TABLE_NAME, DQ_DIMENSION, PASS_PCT ASC;

-- Top failing checks
SELECT
    TABLE_NAME || ' › ' || CHECK_NAME AS check_label,
    FAIL_COUNT,
    FAIL_PCT
FROM DQ_METRICS_LOG
WHERE RUN_TIMESTAMP = (SELECT MAX(RUN_TIMESTAMP) FROM DQ_METRICS_LOG)
ORDER BY FAIL_COUNT DESC
LIMIT 10;


-- Overall health score per table 
SELECT
    TABLE_NAME,
    ROUND(AVG(PASS_PCT), 1) AS overall_dq_score_pct
FROM DQ_METRICS_LOG
WHERE RUN_TIMESTAMP = (SELECT MAX(RUN_TIMESTAMP) FROM DQ_METRICS_LOG)
GROUP BY TABLE_NAME
ORDER BY TABLE_NAME;


-- Trend over runs 
SELECT
    DATE_TRUNC('HOUR', RUN_TIMESTAMP) AS run_hour,
    TABLE_NAME,
    ROUND(AVG(PASS_PCT), 1)           AS avg_pass_pct
FROM DQ_METRICS_LOG
GROUP BY 1, 2
ORDER BY 1, 2;

-- Flagged customer rows 
SELECT *
FROM VW_CUSTOMER_DQ
WHERE row_dq_status = 'FLAGGED'
ORDER BY CUSTOMER_ID;

-- Flagged order rows drill-down
SELECT *
FROM VW_ORDER_DQ
WHERE row_dq_status = 'FLAGGED'
ORDER BY ORDER_ID;